---
plugins:
  # https://github.com/jest-community/eslint-plugin-import
  - import

# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
  node: true

extends:
  - 'airbnb-base'
  - 'plugin:import/recommended'

rules:
  no-console: 0
  import/extensions: 0