name: github-active-node-ci
on: [push, pull_request]
jobs:
  testLint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build
      run: make install
      env:
        CI: true
    - name: makeLint
      run: make lint
