name: node-ci
on: [push, pull_request]
jobs:
  testLint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node: '13.14.0'
    - name: npm install, build
      run: make install
      env:
        CI: true
    - name: makeLint
      run: make lint
